import pdfplumber
import re
import sys

pdf_path = r'C:\Users\bruno\projects\btas\references\Bruno Tachinardi - CV [EN].pdf'

# Word and phrase level corrections
word_corrections = {
    # Tech terms
    'TensorKow': 'TensorFlow',
    'Ueras': 'Keras',
    'Wnity3d': 'Unity3d',
    'Wnity': 'Unity',
    'veact': 'React',
    'Vue R veact': 'Vue & React',
    '#indows': 'Windows',
    '#eb': 'Web',
    '#ord': 'Word',
    '#ork': 'Work',
    '#orked': 'Worked',
    '#ellness': 'Wellness',
    'S/L': 'SQL',
    'CQ': 'C#',
    'CX': 'C#',
    'vesNet': 'ResNet',
    'veal-Time': 'Real-Time',
    'vecognition': 'Recognition',
    'vecognized': 'Recognized',
    'veport': 'Report',
    'vesearch': 'Research',
    'vewards': 'Rewards',
    'vesources': 'Resources',
    'vesilience': 'Resilience',
    'vuntime': 'Runtime',
    'veader': 'Reader',
    'vepurpos': 'Repurpos',

    # Business terms
    'B2B': 'B2B',
    'MJP': 'MVP',
    'MV-P': 'MVP',
    'M-P': 'MVP',
    'ARB': 'A/B',
    'Hv': 'HR',
    'vJ': 'R$',
    'PoC': 'PoC',
    'CIRCD': 'CI/CD',
    'De2Ops': 'DevOps',
    'SCOvM': 'SCORM',
    'SWS': 'SUS',

    # Companies/Names
    'bukanR': 'Nubank',
    'Wnimed': 'Unimed',
    'Jamkon': 'Zambon',
    'Zella': 'Wella',
    'MCS xava': 'MCS Java',
    'Anhemki Morumki': 'Anhembi Morumbi',
    'S_rio-Liban s': 'Sirio-Libanes',

    # Common encoded patterns
    'O2er2iew': 'Overview',
    'de2elop': 'develop',
    'De2elop': 'Develop',
    'inno2ati2e': 'innovative',
    'Inno2ati2e': 'Innovative',
    'inno2ation': 'innovation',
    'Inno2ation': 'Innovation',
    'pi2ot': 'pivot',
    'pi2otal': 'pivotal',
    'acti2it': 'activit',
    'Acti2it': 'Activit',
    'eqpand': 'expand',
    'eqpans': 'expans',
    'eqten': 'exten',
    'eqist': 'exist',
    'eqpert': 'expert',
    'eqecut': 'execut',
    'eqplor': 'explor',
    'eqpress': 'express',
    'Eqpress': 'Express',
    'eqcel': 'excel',
    'Eqcel': 'Excel',
    'eqperience': 'experience',
    'Eqperience': 'Experience',
    'eqperiment': 'experiment',
    'Eqperiment': 'Experiment',
    'e2ent': 'event',
    'E2ent': 'Event',
    'e2eris': 'Everis',
    'a2erage': 'average',
    'a2atar': 'avatar',
    'na2igat': 'navigat',
    'pro2id': 'provid',
    'impro2': 'improv',
    'o2er ': 'over ',
    'o2erall': 'overall',
    'disco2er': 'discover',
    'reco2er': 'recover',
    'co2er': 'cover',
    'ser2': 'serv',
    'reser2': 'reserv',
    'obser2': 'observ',
    'preser2': 'preserv',
    'achie2': 'achiev',
    'Achie2': 'Achiev',
    'recei2': 'receiv',
    'belie2': 'believ',
    'rele2': 'relev',
    '2alid': 'valid',
    '-alid': 'Valid',
    '2alu': 'valu',
    '2ari': 'vari',
    '2ision': 'vision',
    '2oice': 'voice',
    '2oter': 'voter',
    '2oted': 'voted',
    'ad2anc': 'advanc',
    'Ad2anc': 'Advanc',
    'ad2oc': 'advoc',
    'beha2ior': 'behavior',
    'Beha2ior': 'Behavior',
    'collaborati2e': 'collaborative',
    'competiti2e': 'competitive',
    'comprehensi2e': 'comprehensive',
    'creati2e': 'creative',
    'Creati2e': 'Creative',
    'dri2en': 'driven',
    'effecti2e': 'effective',
    'enga2e': 'engage',
    'E2eris': 'Everis',
    'executi2e': 'executive',
    'extensi2e': 'extensive',

    # Percent/fi patterns
    'gami%': 'gamifi',
    'Gami%': 'Gamifi',
    '%cation': 'fication',
    '%ciency': 'ficiency',
    '%ed': 'fied',
    '%er': 'fier',
    '%ne': 'fine',
    '%rst': 'first',
    '%nd': 'find',
    '%le': 'file',
    '%lter': 'filter',
    '%nal': 'final',
    '%nancial': 'financial',
    '%nish': 'finish',
    '%rm': 'firm',
    'ef%c': 'effic',
    'bene%t': 'benefit',
    'identi%': 'identifi',
    'Identi%': 'Identifi',
    'certi%': 'certifi',
    'speci%': 'specifi',
    'signi%': 'signifi',
    'Signi%': 'Signifi',
    'quali%': 'qualifi',
    'rati%': 'ratifi',
    'veri%': 'verifi',
    'noti%': 'notifi',
    'modi%': 'modifi',
    'ampli%': 'amplifi',
    'simpli%': 'simplifi',
    'pro%le': 'profile',
    'Pro%le': 'Profile',

    # K patterns (fl)
    'reKect': 'reflect',
    'reKin': 'refin',
    'Kedge': 'fledge',
    'Kow': 'flow',
    'Kuid': 'fluid',
    'airKow': 'airflow',
    'workKow': 'workflow',

    # More v patterns
    'in2est': 'invest',
    'In2est': 'Invest',
    'in2ol2': 'involv',
    'In2ol2': 'Involv',
    'interacti2e': 'interactive',
    'intuiti2e': 'intuitive',
    'le2erag': 'leverag',
    'li2es': 'lives',
    'moti2': 'motiv',
    'nati2e': 'native',
    'negati2e': 'negative',
    'ob8ecti2e': 'objective',
    'ob8ect': 'object',
    'pro8ect': 'project',
    'Pro8ect': 'Project',
    'positi2e': 'positive',
    'producti2e': 'productive',
    'progressi2e': 'progressive',
    'reacti2e': 'reactive',
    'relati2e': 'relative',
    'responsi2e': 'responsive',
    'sensiti2e': 'sensitive',
    'supporti2e': 'supportive',
    'sur2ey': 'survey',
    're2eal': 'reveal',
    're2iew': 'review',
    'Re2iew': 'Review',
    're2ol': 'revol',
    'Re2ol': 'Revol',
    'deli2er': 'deliver',
    'Deli2er': 'Deliver',
    'di2er': 'diver',
    'Di2er': 'Diver',
    'dri2e': 'drive',
    'Dri2e': 'Drive',
    'gi2e': 'give',
    'li2e': 'live',
    'Li2e': 'Live',
    'pri2a': 'priva',
    'uni2ers': 'univers',
    'Uni2ers': 'Univers',
    'sol2': 'solv',
    'Sol2': 'Solv',
    're2enue': 'revenue',
    'ser2er': 'server',
    'con2er': 'conver',
    'con2ert': 'convert',

    # 8 patterns (j)
    '8ourney': 'journey',
    '8oin': 'join',
    '8unior': 'junior',
    '8ury': 'jury',
    '8ust': 'just',
    '8SON': 'JSON',
    'ma8or': 'major',
    'Ma8or': 'Major',
    'en8oy': 'enjoy',
    'sub8ect': 'subject',
    'ad8ust': 'adjust',

    # $ patterns (q)
    '$uality': 'quality',
    '/uality': 'Quality',
    '$uery': 'query',
    '$uestion': 'question',
    '$uick': 'quick',
    'techni$ue': 'technique',
    'uni$ue': 'unique',
    're$uire': 'require',
    'Re$uire': 'Require',
    'ac$uisition': 'acquisition',
    'se$uen': 'sequen',
    'conse$uen': 'consequen',
    'fre$uen': 'frequen',

    # Date/time patterns
    'FEBvWAvY': 'FEBRUARY',
    'JanuarY': 'January',
    'JANWAvY': 'JANUARY',
    'JUNE': 'JUNE',
    'JULY': 'JULY',
    'MAvCH': 'MARCH',
    'APvIL': 'APRIL',
    'NOVEMBEv': 'NOVEMBER',
    'OCTOBEv': 'OCTOBER',
    'DECEMBEv': 'DECEMBER',
    'SEPTEMBEv': 'SEPTEMBER',
    'PvESENT': 'PRESENT',

    # Section headers
    'jesponsibilities': 'Responsibilities',
    'jesponsikilities': 'Responsibilities',
    'jesearch': 'Research',
    'jeNnement': 'Refinement',
    'jeNne': 'Refine',
    'joadmap': 'Roadmap',
    'jole': 'Role',
    'jound': 'Round',
    'Contrikutions': 'Contributions',
    'Contrikut': 'Contribut',
    'Collakora': 'Collabora',
    'Puklication': 'Publication',
    'Puklish': 'Publish',
    'StaReholders': 'Stakeholders',
    'GamiNcation': 'Gamification',

    # Special characters
    '(ealth': 'Health',
    '(orizonte': 'Horizonte',
    '(ouse': 'House',
    '(onorable': 'Honorable',
    '(ospital': 'Hospital',
}

def decode_text(text):
    result = text

    # Apply word/phrase corrections (longest first)
    for wrong, correct in sorted(word_corrections.items(), key=lambda x: -len(x[0])):
        result = result.replace(wrong, correct)

    # Fix remaining year patterns
    result = re.sub(r'2([0-9]{3})', r'2\1', result)  # Keep years like 2019

    # Fix bullet points (5 at start of line)
    result = re.sub(r'^5 ', '- ', result, flags=re.MULTILINE)
    result = re.sub(r'\n5 ', '\n- ', result)

    return result

# Extract and decode
with pdfplumber.open(pdf_path) as pdf:
    for i, page in enumerate(pdf.pages):
        text = page.extract_text()
        if text:
            decoded = decode_text(text)
            print(f'=== PAGE {i+1} ===')
            print(decoded)
            print()
